(function() {var implementors = {};
implementors["odbc_safe"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"odbc_sys/sqlreturn/enum.SQLRETURN.html\" title=\"enum odbc_sys::sqlreturn::SQLRETURN\">SQLRETURN</a>&gt; for <a class=\"enum\" href=\"odbc_safe/enum.Return.html\" title=\"enum odbc_safe::Return\">Return</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.unit.html\">()</a>&gt;",synthetic:false,types:["odbc_safe::return_::Return"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"odbc_sys/sqlreturn/enum.SQLRETURN.html\" title=\"enum odbc_sys::sqlreturn::SQLRETURN\">SQLRETURN</a>&gt; for <a class=\"enum\" href=\"odbc_safe/enum.ReturnOption.html\" title=\"enum odbc_safe::ReturnOption\">ReturnOption</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.unit.html\">()</a>&gt;",synthetic:false,types:["odbc_safe::return_option::ReturnOption"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.i64.html\">i64</a>&gt; for <a class=\"enum\" href=\"odbc_safe/enum.Indicator.html\" title=\"enum odbc_safe::Indicator\">Indicator</a>",synthetic:false,types:["odbc_safe::indicator::Indicator"]},];
implementors["odbc_sys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"odbc_sys/enum.OdbcVersion.html\" title=\"enum odbc_sys::OdbcVersion\">OdbcVersion</a>&gt; for <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.pointer.html\">*mut </a><a class=\"enum\" href=\"https://doc.rust-lang.org/nightly/core/ffi/enum.c_void.html\" title=\"enum core::ffi::c_void\">c_void</a>",synthetic:false,types:["core::ffi::c_void"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()